import time

from benchmark.benchmark_runner import BenchmarkResults


def generate_markdown_report(
    model: str,
    benchmark_results: BenchmarkResults,
    endpoint_creation_time_seconds: float,
    time_to_ready_seconds: float,
    deletion_time_seconds: float | None = None,
) -> str:
    timestamp = time.strftime("%Y-%m-%d %H:%M:%S UTC", time.gmtime())
    r = benchmark_results

    lifecycle_rows: list[tuple[str, str]] = [
        ("Model",                   model),
        ("Timestamp",               timestamp),
        ("Endpoint Creation Time",  f"{endpoint_creation_time_seconds:.1f}s"),
        ("Time To Ready",           f"{time_to_ready_seconds:.1f}s"),
    ]
    if deletion_time_seconds is not None:
        lifecycle_rows.append(("Deletion Time", f"{deletion_time_seconds:.1f}s"))

    latency_rows: list[tuple[str, str]] = [
        ("TTFT",                    f"{r.ttft.ttft_ms:.0f}ms"),
        ("ITL Mean",                f"{r.itl.mean_itl_ms:.1f}ms"),
        ("ITL p50",                 f"{r.itl.p50_itl_ms:.1f}ms"),
        ("ITL p90",                 f"{r.itl.p90_itl_ms:.1f}ms"),
        ("ITL p99",                 f"{r.itl.p99_itl_ms:.1f}ms"),
        ("Token Generation Speed",  f"{r.itl.tokens_per_second:.1f} tok/s"),
        ("E2E Latency (single)",    f"{r.latency.latency_ms:.0f}ms"),
    ]

    percentile_rows: list[tuple[str, str]] = [
        ("p50 Latency",             f"{r.percentiles.p50_ms:.0f}ms"),
        ("p90 Latency",             f"{r.percentiles.p90_ms:.0f}ms"),
        ("p99 Latency",             f"{r.percentiles.p99_ms:.0f}ms"),
        ("Mean Latency",            f"{r.percentiles.mean_ms:.0f}ms"),
        ("Min / Max",               f"{r.percentiles.min_ms:.0f}ms / {r.percentiles.max_ms:.0f}ms"),
        ("Std Dev",                 f"{r.percentiles.std_ms:.0f}ms"),
        ("Sample Count",            str(r.percentiles.sample_count)),
    ]

    throughput_rows: list[tuple[str, str]] = [
        ("Requests/sec",            f"{r.throughput.requests_per_second:.2f} rps"),
        ("Token Throughput",        f"{r.throughput.tokens_per_second:.1f} tok/s"),
        ("Total Output Tokens",     str(r.throughput.total_output_tokens)),
        ("Success Rate",            f"{r.throughput.success_rate * 100:.1f}%"),
        ("Requests (ok/total)",     f"{r.throughput.successful_requests}/{r.throughput.total_requests}"),
    ]

    def _table(rows: list[tuple[str, str]]) -> str:
        return "| Metric | Value |\n|--------|-------|\n" + "\n".join(
            f"| {k} | {v} |" for k, v in rows
        )

    return f"""# Nebius AI Endpoint Benchmark Report

## Lifecycle

{_table(lifecycle_rows)}

## Latency

{_table(latency_rows)}

## Latency Distribution ({r.percentiles.sample_count} samples)

{_table(percentile_rows)}

## Throughput

{_table(throughput_rows)}

---

**Endpoint URL**: `{r.endpoint_url}`

*Generated by Nebius Endpoint Lab*
"""
