"""Report Center — generate and download JSON, Markdown, and HTML reports from any past run."""

from __future__ import annotations

import json
import sys
import time
from pathlib import Path
from typing import Any

import streamlit as st

ROOT = Path(__file__).parent.parent.parent
sys.path.insert(0, str(ROOT))

from database.migrations import get_session_factory
from database.repository import BenchmarkRepository

st.set_page_config(page_title="Reports · Nebius Endpoint Lab", page_icon="📄", layout="wide")


@st.cache_resource
def _factory():
    return get_session_factory()


def _repo():
    return BenchmarkRepository(_factory()())


# ── helpers ────────────────────────────────────────────────────────────────────

def _build_json(run: dict[str, Any], conc: list[dict]) -> str:
    report: dict = {
        "run_id":   run["run_id"],
        "model":    run["model_id"],
        "timestamp": run["timestamp"].isoformat() if run.get("timestamp") else None,
        "platform": run.get("platform"),
        "deployment": {
            "endpoint_creation_time_s": run.get("creation_s"),
            "time_to_ready_s":          run.get("ttr_s"),
            "deletion_time_s":          run.get("deletion_s"),
        },
        "ttft_ms":                    run.get("ttft_ms"),
        "itl_mean_ms":                run.get("itl_mean_ms"),
        "itl_p90_ms":                 run.get("itl_p90_ms"),
        "tok_per_s":                  run.get("tok_per_s"),
        "latency_ms":                 run.get("latency_ms"),
        "lat_p50_ms":                 run.get("lat_p50_ms"),
        "lat_p90_ms":                 run.get("lat_p90_ms"),
        "lat_p99_ms":                 run.get("lat_p99_ms"),
        "requests_per_second":        run.get("rps"),
        "throughput_tokens_per_second": run.get("tput_tok_s"),
        "success_rate":               run.get("success_rate"),
        "concurrency": conc,
    }
    return json.dumps(report, indent=2, default=str)


def _build_markdown(run: dict[str, Any], conc: list[dict]) -> str:
    ts = run["timestamp"].strftime("%Y-%m-%d %H:%M UTC") if run.get("timestamp") else "—"

    def _v(val, fmt=".0f", unit="") -> str:
        return f"{val:{fmt}}{unit}" if val is not None else "—"

    rows = [
        ("Run ID",          run["run_id"]),
        ("Model",           run["model"]),
        ("Timestamp",       ts),
        ("Platform",        run.get("platform") or "—"),
        ("Time → Ready",    _v(run.get("ttr_s"),        ".0f", "s")),
        ("TTFT",            _v(run.get("ttft_ms"),      ".0f", "ms")),
        ("ITL Mean",        _v(run.get("itl_mean_ms"),  ".1f", "ms")),
        ("ITL p90",         _v(run.get("itl_p90_ms"),   ".1f", "ms")),
        ("E2E Latency",     _v(run.get("latency_ms"),   ".0f", "ms")),
        ("p50 / p90 / p99", f"{_v(run.get('lat_p50_ms'),'.0f')} / {_v(run.get('lat_p90_ms'),'.0f')} / {_v(run.get('lat_p99_ms'),'.0f')} ms"),
        ("Throughput",      _v(run.get("rps"),          ".2f", " rps")),
        ("Token Throughput",_v(run.get("tput_tok_s"),   ".1f", " tok/s")),
        ("Success Rate",    _v(run.get("success_rate"), ".1%")),
    ]
    table = "| Metric | Value |\n|--------|-------|\n" + "\n".join(f"| {k} | {v} |" for k, v in rows)

    conc_section = ""
    if conc:
        conc_header = "| Concurrency | RPS | p95 Lat (ms) | Success Rate |\n|---|---|---|---|\n"
        conc_rows   = "\n".join(
            f"| {c['concurrency']} | {c['rps']:.2f} | {c['p95_ms']:.0f} | {c['success_rate']*100:.1f}% |"
            for c in conc if c.get("rps") is not None
        )
        conc_section = f"\n\n## Concurrency Analysis\n\n{conc_header}{conc_rows}"

    return f"# Nebius Benchmark Report\n\n## Summary\n\n{table}{conc_section}\n\n---\n*Generated by Nebius Endpoint Lab*\n"


def _build_html(run: dict[str, Any], conc: list[dict]) -> str:
    import plotly.graph_objects as go
    ts = run["timestamp"].strftime("%Y-%m-%d %H:%M UTC") if run.get("timestamp") else "—"

    def _v(val, fmt=".0f", unit="") -> str:
        return f"{val:{fmt}}{unit}" if val is not None else "—"

    def _row(k, v):
        return f"<tr><td>{k}</td><td><strong>{v}</strong></td></tr>"

    rows_html = "\n".join([
        _row("Run ID",          run["run_id"]),
        _row("Model",           run["model"]),
        _row("Timestamp",       ts),
        _row("Time → Ready",    _v(run.get("ttr_s"),".0f","s")),
        _row("TTFT",            _v(run.get("ttft_ms"),".0f","ms")),
        _row("ITL p90",         _v(run.get("itl_p90_ms"),".1f","ms")),
        _row("p50/p90/p99",     f"{_v(run.get('lat_p50_ms'),'.0f')} / {_v(run.get('lat_p90_ms'),'.0f')} / {_v(run.get('lat_p99_ms'),'.0f')} ms"),
        _row("Throughput",      _v(run.get("rps"),".2f"," rps")),
        _row("Success Rate",    _v(run.get("success_rate"),".1%")),
    ])

    pct_vals = [run.get(k) or 0 for k in ["lat_p50_ms","lat_p90_ms","lat_p99_ms"]]
    fig_pct  = go.Figure(go.Bar(x=["p50","p90","p99"], y=pct_vals,
                                marker_color=["#636EFA","#EF553B","#FF6692"],
                                text=[f"{v:.0f}ms" for v in pct_vals], textposition="outside"))
    fig_pct.update_layout(title="Latency Percentiles", height=320, template="plotly_dark")
    pct_div = fig_pct.to_html(full_html=False, include_plotlyjs=False)

    conc_div = ""
    if conc:
        fig_c = go.Figure(go.Scatter(
            x=[c["concurrency"] for c in conc],
            y=[c["rps"] for c in conc],
            mode="lines+markers", marker_color="#636EFA",
        ))
        fig_c.update_layout(title="Throughput vs Concurrency", height=320, template="plotly_dark",
                            xaxis_title="Concurrency", yaxis_title="rps")
        conc_div = f"<h2>Concurrency</h2><div class='card'>{fig_c.to_html(full_html=False, include_plotlyjs=False)}</div>"

    return f"""<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"/>
<title>Report · {run['model']}</title>
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
<style>
body{{font-family:system-ui,sans-serif;background:#0e1117;color:#e0e0e0;margin:0;padding:0}}
.wrap{{max-width:1000px;margin:0 auto;padding:32px 24px}}
h1{{color:#636EFA}}h2{{color:#aaa;font-size:.9rem;text-transform:uppercase;letter-spacing:.08em;margin:28px 0 10px;border-bottom:1px solid #333;padding-bottom:4px}}
table{{border-collapse:collapse;width:100%;max-width:500px}}
td{{padding:8px 12px;border-bottom:1px solid #333;font-size:.88rem}}td:first-child{{color:#888;width:200px}}
.card{{background:#1a1d27;border:1px solid #2a2d3a;border-radius:8px;padding:16px;margin-bottom:16px}}
footer{{margin-top:40px;color:#555;font-size:.75rem;text-align:center}}
</style></head><body><div class="wrap">
<h1>🔬 Benchmark Report</h1>
<p style="color:#888">Model: {run['model']} &nbsp;·&nbsp; {ts}</p>
<h2>Summary</h2><table>{rows_html}</table>
<h2>Latency Distribution</h2><div class="card">{pct_div}</div>
{conc_div}
<footer>Generated by Nebius Endpoint Lab</footer>
</div></body></html>"""


# ── page ────────────────────────────────────────────────────────────────────────

st.title("📄 Report Center")
st.caption("Generate and download reports from any stored benchmark run")
st.divider()

try:
    runs = _repo().list_runs(limit=200)
except Exception as exc:
    st.error(f"DB error: {exc}"); st.stop()

if not runs:
    st.info("No benchmark runs stored yet.")
    st.stop()

run_options = {
    f"{r['run_id']}  ·  {r['model']}  ·  {r['timestamp'].strftime('%m/%d %H:%M') if r['timestamp'] else ''}": r["run_id"]
    for r in runs
}

selected_label = st.selectbox("Select benchmark run", list(run_options.keys()))
run_id = run_options[selected_label]
run    = next(r for r in runs if r["run_id"] == run_id)

try:
    conc = _repo().get_concurrency_results(run_id)
except Exception:
    conc = []

# ── Run summary ───────────────────────────────────────────────────────────────
st.subheader("Run Summary")
c1, c2, c3, c4 = st.columns(4)
c1.metric("TTFT",      f"{run['ttft_ms']:.0f}ms" if run.get("ttft_ms") else "—")
c2.metric("p90 Lat",   f"{run['lat_p90_ms']:.0f}ms" if run.get("lat_p90_ms") else "—")
c3.metric("Throughput",f"{run['rps']:.2f} rps" if run.get("rps") else "—")
c4.metric("Success",   f"{run['success_rate']*100:.1f}%" if run.get("success_rate") else "—")

st.divider()

# ── Downloads ─────────────────────────────────────────────────────────────────
st.subheader("Download Reports")
ts = int(time.time())
d1, d2, d3 = st.columns(3)
d1.download_button("📥 JSON",     _build_json(run, conc),     f"report_{run_id}_{ts}.json",  "application/json",  use_container_width=True)
d2.download_button("📥 Markdown", _build_markdown(run, conc), f"report_{run_id}_{ts}.md",    "text/markdown",     use_container_width=True)
d3.download_button("📥 HTML",     _build_html(run, conc),     f"report_{run_id}_{ts}.html",  "text/html",         use_container_width=True)
